version: '3.1'

services: 
  teamcity:
    image: jetbrains/teamcity-server:2019.1.2
    volumes: 
      - teamcity-server-datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 81:81
  teamcity-agent:
    image: jetbrains/teamcity-agent:2019.1.2
    environment: 
      SERVER_URL: http://teamcity:81
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  teamcity-server-datadir:
  teamcity-server-logs: